#pull base image
FROM adoptopenjdk:8-jre-hotspot

ADD target/springdockerdemo-1.0.jar

#Maintainer 
MAINTAINER kashyapRBharath

#Expose port 8080
EXPOSE 8098

#default command
ENTRYPOINT ["java","-jar","/tmp/docker/springdockerdemo-1.0.jar"]
