#pull base image
FROM adoptopenjdk:8-jre-hotspot

ADD target/springdockerdemo-1.0.jar springdockerdemo-1.0.jar

#Maintainer 
MAINTAINER kashyapRBharath

#Expose port 8085
EXPOSE 8085

#default command
ENTRYPOINT ["java","-jar","springdockerdemo-1.0.jar"]
